# Confluence YAML config file
#
# Confluence URL
url: "https://stage.its.sfu.ca/atl-conf"

# Credentials to login with
username: admin
password: Password

# If defined, mandatory group that users must be a member of. If they're not, 
# their account gets disabled. Members of mandatory_excluded_group will be
# removed from the mandatory_group set before comparing against Confluence
mandatory_group: confluence-users
mandatory_excluded_group: confluence-users-exclude

# Map of Confluence groups that differ from their respective SFU Maillist
# Format is confluence-group: sfu-maillist
groupMap: 
  confluence-administrators: confluence-admins
  icat: i-cat
  irmacs: confluence-irmacs
  iti-users: iti-staff
  

# Excluded users: users that won't be removed from groups
# Generally this should be any user that exists in Confluence but not Amaint
excluded: 
  - admin
  - confadmin
  - automation
